### ISSUE TITLE
Suggestion: allow to publish themes

### ISSUE THREAD

**Issue by zoechi** [HannesRammer/Rainbow#2]
It would be cool if people could share their themes created on your site.

**Comment by HannesRammer** [comment]
will come ;) 

already thought about saving files on app engine, but then without login it will be difficult to control upload and everything.
before that I need to finish my tutorial for you guys on Dartabase.
then add dartabase to rainbow so I can controll who is uploading what, dont want a bot to spam my system ^^
so currently my time estimation is 1-2 month. 
basically too busy with uni, just wanted to get this out to you guys so you can start creating, till then just add them to my post in dart misc ;)

**Comment by zoechi** [comment]
Great to hear!
